### ISSUE TITLE
SyntaxError Invalid syntax

### ISSUE THREAD

**Issue by davidzwa** [PDOK/nested-dataclasses#1]
A syntactically wrong /

```
Traceback (most recent call last):
  File ".\process.py", line 2, in <module>
    from Model.ParsedData import JsonData, DataEntry, PositionData
  File "RELATIVE_PATH\Model\ParsedData.py", line 3, in <module>
  File "PYTHON_PATH\site-packages\nested_dataclasses\__init__.py", line 46, in <module>
    from nested_dataclasses.nested_dataclass import nested
  File "PYTHON_PATH\nested_dataclasses\nested_dataclass.py", line 83
    def nested(cls=None, /, *, validator=True, to_dict=True):
                         ^
SyntaxError: invalid syntax
```

**Comment by RoelvandenBerg** [comment]
Sorry for the late reply. I think this has to do with the Python version. In recent python3 you can do this (it is inspired by the [python dataclass source](https://github.com/python/cpython/blob/master/Lib/dataclasses.py#L1015)). If I can find some time I'll check if I can make this work for older python3 versions. A nice to have.
